# Generated by Django 4.2.5 on 2023-09-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_lengkap", models.CharField(max_length=200)),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[("L", "pria"), ("P", "Perempuan")],
                        default="L",
                        max_length=20,
                    ),
                ),
                (
                    "agama",
                    models.CharField(
                        choices=[
                            ("Islam", "Islam"),
                            ("Kristen", "Kristen"),
                            ("Katolik", "Katolik"),
                            ("Budha", "Budha"),
                            ("Hindu", "Hindu"),
                            ("Konghucu", "Konghucu"),
                        ],
                        default="Islam",
                        max_length=10,
                    ),
                ),
                ("tempat_lahir", models.CharField(blank=True, max_length=300)),
                (
                    "tanggal_lahir",
                    models.DateField(default="2023/01/01", help_text="Tanggal Lahir"),
                ),
                (
                    "alamat_lengkap",
                    models.CharField(blank=True, default="-", max_length=400),
                ),
                ("kecamatan", models.CharField(default="-", max_length=200)),
                ("kota", models.CharField(default="-", max_length=200)),
                ("provinsi", models.CharField(default="-", max_length=300)),
                ("no_hp", models.CharField(default="+62", max_length=12)),
                ("no_ktp", models.CharField(default="-", max_length=20)),
                ("pekerjaan", models.CharField(default="-", max_length=300)),
                (
                    "status_dalam_keluarga",
                    models.CharField(
                        choices=[
                            ("Suami", "Suami"),
                            ("Istri", "Istri"),
                            ("Anak", "Anak"),
                            ("Menantu", "Menantu"),
                            ("Cucu", "Cucu"),
                            ("Keponakan", "Keponakan"),
                            ("Orang Tua", "Orang Tua"),
                            ("Mertua", "Mertua"),
                        ],
                        default="Suami",
                        max_length=200,
                    ),
                ),
                ("nama_orang_tua", models.CharField(default="-", max_length=200)),
                ("no_hp_pasangan", models.CharField(default="-", max_length=12)),
                ("upload_ktp", models.ImageField(default="-", upload_to="uploadktp/")),
                (
                    "upload_pas_foto",
                    models.ImageField(default="-", upload_to="uploadpasfoto/"),
                ),
            ],
        ),
    ]
