# Generated by Django 4.2.5 on 2023-09-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="tanggal_lahir",
            field=models.DateField(default="1988/01/01", help_text="Tanggal Lahir"),
        ),
    ]
