# Generated by Django 4.2.5 on 2023-09-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Promosi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("logo", models.ImageField(upload_to="logo/")),
                ("keterangan", models.TextField()),
                ("link", models.TextField()),
            ],
        ),
    ]
