# Generated by Django 4.2.5 on 2023-09-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_promosi_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("ket_pendek", models.TextField()),
                ("keterangan", models.TextField()),
                ("slidshow", models.ImageField(upload_to="slidshow/")),
            ],
        ),
    ]
