# Generated by Django 4.2.5 on 2023-09-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_pengurus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visi", models.TextField()),
                ("misi", models.TextField()),
                ("badanhukum", models.CharField(max_length=200)),
                ("perizinan", models.CharField(max_length=200)),
                ("kemenhumham", models.CharField(max_length=200)),
                ("nokementrian", models.CharField(max_length=200)),
                ("noindukkoperasi", models.CharField(max_length=200)),
                ("berdiri", models.CharField(max_length=200)),
                ("logo", models.ImageField(upload_to="upload/")),
            ],
        ),
    ]
